default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 1234569
  host: localhost

development:
  <<: *default
  database: booking_form_development
  username: postgres
  password: 1234569

test:
  <<: *default
  database: booking_form_test
  username: postgres
  password: 1234569

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
